[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git" }

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", default-features = false }
